### ISSUE TITLE
WuaCpuFix won't work on Windows 8.1 with the latest Preview Rollup

### ISSUE THREAD

**Issue by jdev15** [p-lider/WuaCpuFix#2]
With the latest KB4462921, wuaueng.dll in Windows 8.1 was updated to version 7.9.9600.19164 (dated 08/09/2018). Now the unsupported hardware popup always appears and it's not possible to install updates from WU.
In Windows 7 wuaueng.dll has not been updated with the latest October Preview Rollup.

**Comment by p-lider** [comment]
Good day,
I am really sorry for responding so late, but for some reason I did not receive a notification about your issue last year. Because I do not use Windows 8.1 on a daily basis I was not aware of this issue by myself. I have just fixed that problem. You can check if it is working fine for you.
I have also noticed that only Windows 8.1 was affected, in the Windows 7 this tool was working just fine.
